export default [
  { value: "AFN", label: "Afghani" },
  { value: "EUR", label: "Euro" },
  { value: "ALL", label: "Lek" },
  { value: "DZD", label: "Algerian Dinar" },
  { value: "USD", label: "US Dollar" },
  { value: "AOA", label: "Kwanza" },
  { value: "XCD", label: "East Caribbean Dollar" },
  { value: "ARS", label: "Argentine Peso" },
  { value: "AMD", label: "Armenian Dram" },
  { value: "AWG", label: "Aruban Florin" },
  { value: "AUD", label: "Australian Dollar" },
  { value: "AZN", label: "Azerbaijan Manat" },
  { value: "BSD", label: "Bahamian Dollar" },
  { value: "BHD", label: "Bahraini Dinar" },
  { value: "BDT", label: "Taka" },
  { value: "BBD", label: "Barbados Dollar" },
  { value: "BYN", label: "Belarusian Ruble" },
  { value: "BZD", label: "Belize Dollar" },
  { value: "XOF", label: "CFA Franc BCEAO" },
  { value: "BMD", label: "Bermudian Dollar" },
  { value: "INR", label: "Indian Rupee" },
  { value: "BTN", label: "Ngultrum" },
  { value: "BOB", label: "Boliviano" },
  { value: "BAM", label: "Convertible Mark" },
  { value: "BWP", label: "Pula" },
  { value: "NOK", label: "Norwegian Krone" },
  { value: "BRL", label: "Brazilian Real" },
  { value: "BND", label: "Brunei Dollar" },
  { value: "BGN", label: "Bulgarian Lev" },
  { value: "BIF", label: "Burundi Franc" },
  { value: "CVE", label: "Cabo Verde Escudo" },
  { value: "KHR", label: "Riel" },
  { value: "XAF", label: "CFA Franc BEAC" },
  { value: "CAD", label: "Canadian Dollar" },
  { value: "KYD", label: "Cayman Islands Dollar" },
  { value: "CLP", label: "Chilean Peso" },
  { value: "CNY", label: "Yuan Renminbi" },
  { value: "COP", label: "Colombian Peso" },
  { value: "KMF", label: "Comorian Franc " },
  { value: "CDF", label: "Congolese Franc" },
  { value: "NZD", label: "New Zealand Dollar" },
  { value: "CRC", label: "Costa Rican Colon" },
  { value: "HRK", label: "Kuna" },
  { value: "CUP", label: "Cuban Peso" },
  { value: "CUC", label: "Peso Convertible" },
  { value: "ANG", label: "Netherlands Antillean Guilder" },
  { value: "CZK", label: "Czech Koruna" },
  { value: "DKK", label: "Danish Krone" },
  { value: "DJF", label: "Djibouti Franc" },
  { value: "DOP", label: "Dominican Peso" },
  { value: "EGP", label: "Egyptian Pound" },
  { value: "SVC", label: "El Salvador Colon" },
  { value: "ERN", label: "Nakfa" },
  { value: "SZL", label: "Lilangeni" },
  { value: "ETB", label: "Ethiopian Birr" },
  { value: "FKP", label: "Falkland Islands Pound" },
  { value: "FJD", label: "Fiji Dollar" },
  { value: "XPF", label: "CFP Franc" },
  { value: "GMD", label: "Dalasi" },
  { value: "GEL", label: "Lari" },
  { value: "GHS", label: "Ghana Cedi" },
  { value: "GIP", label: "Gibraltar Pound" },
  { value: "GTQ", label: "Quetzal" },
  { value: "GBP", label: "Pound Sterling" },
  { value: "GNF", label: "Guinean Franc" },
  { value: "GYD", label: "Guyana Dollar" },
  { value: "HTG", label: "Gourde" },
  { value: "HNL", label: "Lempira" },
  { value: "HKD", label: "Hong Kong Dollar" },
  { value: "HUF", label: "Forint" },
  { value: "ISK", label: "Iceland Krona" },
  { value: "IDR", label: "Rupiah" },
  { value: "XDR", label: "SDR (Special Drawing Right)" },
  { value: "IRR", label: "Iranian Rial" },
  { value: "IQD", label: "Iraqi Dinar" },
  { value: "ILS", label: "New Israeli Sheqel" },
  { value: "JMD", label: "Jamaican Dollar" },
  { value: "JPY", label: "Yen" },
  { value: "JOD", label: "Jordanian Dinar" },
  { value: "KZT", label: "Tenge" },
  { value: "KES", label: "Kenyan Shilling" },
  { value: "KPW", label: "North Korean Won" },
  { value: "KRW", label: "Won" },
  { value: "KWD", label: "Kuwaiti Dinar" },
  { value: "KGS", label: "Som" },
  { value: "LAK", label: "Lao Kip" },
  { value: "LBP", label: "Lebanese Pound" },
  { value: "LSL", label: "Loti" },
  { value: "ZAR", label: "Rand" },
  { value: "LRD", label: "Liberian Dollar" },
  { value: "LYD", label: "Libyan Dinar" },
  { value: "CHF", label: "Swiss Franc" },
  { value: "MOP", label: "Pataca" },
  { value: "MKD", label: "Denar" },
  { value: "MGA", label: "Malagasy Ariary" },
  { value: "MWK", label: "Malawi Kwacha" },
  { value: "MYR", label: "Malaysian Ringgit" },
  { value: "MVR", label: "Rufiyaa" },
  { value: "MRU", label: "Ouguiya" },
  { value: "MUR", label: "Mauritius Rupee" },
  { value: "XUA", label: "ADB Unit of Account" },
  { value: "MXN", label: "Mexican Peso" },
  { value: "MDL", label: "Moldovan Leu" },
  { value: "MNT", label: "Tugrik" },
  { value: "MAD", label: "Moroccan Dirham" },
  { value: "MZN", label: "Mozambique Metical" },
  { value: "MMK", label: "Kyat" },
  { value: "NAD", label: "Namibia Dollar" },
  { value: "NPR", label: "Nepalese Rupee" },
  { value: "NIO", label: "Cordoba Oro" },
  { value: "NGN", label: "Naira" },
  { value: "OMR", label: "Rial Omani" },
  { value: "PKR", label: "Pakistan Rupee" },
  { value: "PAB", label: "Balboa" },
  { value: "PGK", label: "Kina" },
  { value: "PYG", label: "Guarani" },
  { value: "PEN", label: "Sol" },
  { value: "PHP", label: "Philippine Peso" },
  { value: "PLN", label: "Zloty" },
  { value: "QAR", label: "Qatari Rial" },
  { value: "RON", label: "Romanian Leu" },
  { value: "RUB", label: "Russian Ruble" },
  { value: "RWF", label: "Rwanda Franc" },
  { value: "SHP", label: "Saint Helena Pound" },
  { value: "WST", label: "Tala" },
  { value: "STN", label: "Dobra" },
  { value: "SAR", label: "Saudi Riyal" },
  { value: "RSD", label: "Serbian Dinar" },
  { value: "SCR", label: "Seychelles Rupee" },
  { value: "SLL", label: "Leone" },
  { value: "SGD", label: "Singapore Dollar" },
  { value: "XSU", label: "Sucre" },
  { value: "SBD", label: "Solomon Islands Dollar" },
  { value: "SOS", label: "Somali Shilling" },
  { value: "SSP", label: "South Sudanese Pound" },
  { value: "LKR", label: "Sri Lanka Rupee" },
  { value: "SDG", label: "Sudanese Pound" },
  { value: "SRD", label: "Surinam Dollar" },
  { value: "SEK", label: "Swedish Krona" },
  { value: "SYP", label: "Syrian Pound" },
  { value: "TWD", label: "New Taiwan Dollar" },
  { value: "TJS", label: "Somoni" },
  { value: "TZS", label: "Tanzanian Shilling" },
  { value: "THB", label: "Baht" },
  { value: "TOP", label: "Pa’anga" },
  { value: "TTD", label: "Trinidad and Tobago Dollar" },
  { value: "TND", label: "Tunisian Dinar" },
  { value: "TRY", label: "Turkish Lira" },
  { value: "TMT", label: "Turkmenistan New Manat" },
  { value: "UGX", label: "Uganda Shilling" },
  { value: "UAH", label: "Hryvnia" },
  { value: "AED", label: "UAE Dirham" },
  { value: "UYU", label: "Peso Uruguayo" },
  { value: "UYW", label: "Unidad Previsional" },
  { value: "UZS", label: "Uzbekistan Sum" },
  { value: "VUV", label: "Vatu" },
  { value: "VES", label: "Bolívar Soberano" },
  { value: "VND", label: "Dong" },
  { value: "YER", label: "Yemeni Rial" },
  { value: "ZMW", label: "Zambian Kwacha" },
  { value: "ZWL", label: "Zimbabwe Dollar" },
  { value: "XBA", label: "Bond Markets Unit European Composite Unit (EURCO)" },
  {
    value: "XBB",
    label: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
  },
  {
    value: "XBC",
    label: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
  },
  {
    value: "XBD",
    label: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
  },
  { value: "XTS", label: "Codes specifically reserved for testing purposes" },
  {
    value: "XXX",
    label: "The codes assigned for transactions where no currency is involved",
  },
  { value: "XAU", label: "Gold" },
  { value: "XPD", label: "Palladium" },
  { value: "XPT", label: "Platinum" },
  { value: "XAG", label: "Silver" },
];
